name: Votes
main: to.joe.j2mc.votes.J2MC_Votes
version: 0.1
website: http://joe.to
author: Eviltechie
description: Voting plugin
commands:
  vote:
    description: Vote on stuff
    usage: /vote
    permission: j2mc.votes.vote
    permission-message: You may not vote
permissions:
  j2mc.votes.vote:
    description: Vote on stuff
  j2mc.votes.newvote:
    description: Make votes
    children:
      j2mc.votes.vote: true
  j2mc.votes.cancel:
    description: Cancel votes
    children:
      j2mc.votes.vote: true
  j2mc.votes.*:
    description: All vote perms
    children:
      j2mc.votes.newvote: true
      j2mc.votes.cancel: true